version: "3"
services:
  bruh:
    container_name: "bruh"
    build:
      context: .
    volumes:
      - bruh:/data
    stop_signal: SIGINT
    restart: unless-stopped
    command: "python -m hikka"
    ports:
      - "${EXTERNAL_PORT:-80}:80"

volumes:
  bruh:
