version: "3"
services:
  bruh:
    container_name: "bruh"
    build:
      context: .
    volumes:
      - bruh:/data
    stop_signal: SIGINT
    restart: unless-stopped
    ports:
      - "${EXTERNAL_PORT:-8080}:8080"

volumes:
  bruh:
